package pers.sxqsachin.mtgsearcher.struct.mtg;

import pers.sxqsachin.mtgsearcher.struct.StringPair;

/**
 *
 * AllEdition
 *
 * Created by songxinqi-sachin on 16-7-16.
 */
public class AllEdition {

    public static StringPair[]  AllEdition  =   new StringPair[] {
            new StringPair("依尼翠暗影", "soi/cn"),
            new StringPair("守护者誓约", "ogw/cn"),
            new StringPair("再战赞迪卡", "bfz/cn"),
            new StringPair("龙命殊途", "frf/cn"),
            new StringPair("鞑契可汗", "ktk/cn"),
            new StringPair("尼兹之旅", "jou/cn"),
            new StringPair("天神创生", "bng/cn"),
            new StringPair("Theros", "ths/cn"),
            new StringPair("巨龙迷城", "dgm/cn"),
            new StringPair("兵临古城", "gtc/cn"),
            new StringPair("再访拉尼卡", "rtr/cn"),
            new StringPair("艾维欣重临", "avr/cn"),
            new StringPair("黑影笼罩", "dka/cn"),
            new StringPair("依尼翠", "isd/cn"),
            new StringPair("新非瑞克西亚", "nph/cn"),
            new StringPair("围攻秘罗地", "mbs/cn"),
            new StringPair("秘罗地创痕", "som/cn"),
            new StringPair("奥札奇再起", "roe/cn"),
            new StringPair("天地醒转", "wwk/cn"),
            new StringPair("赞迪卡", "zen/cn"),
            new StringPair("Alara Reborn", "arb/cn"),
            new StringPair("聚流", "cfx/cn"),
            new StringPair("阿拉若断片", "ala/cn"),
            new StringPair("暮光", "eve/cn"),
            new StringPair("暗影荒原", "shm/cn"),
            new StringPair("晨光", "mt/cn"),
            new StringPair("洛温", "lw/cn"),
            new StringPair("预知将来", "fut/cn"),
            new StringPair("时空混沌", "pc/cn"),
            new StringPair("Time Spiral", "ts/cn"),
            new StringPair("Time Spiral  \"Timeshifted\"", "tsts/cn"),
            new StringPair("骤霜", "cs/cn"),
            new StringPair("纷争", "di/cn"),
            new StringPair("十會盟", "gp/cn"),
            new StringPair("拉尼卡公会城", "rav/cn"),
            new StringPair("Saviors of Kamigawa", "sok/cn"),
            new StringPair("神河叛将谱", "bok/cn"),
            new StringPair("神河群英录", "chk/cn"),
            new StringPair("五色曙光", "5dn/cn"),
            new StringPair("玄铁", "ds/cn"),
            new StringPair("万智牌：起源", "ori/cn"),
            new StringPair("Magic 2015", "m15/cn"),
            new StringPair("魔法風雲會2014核心系列", "m14/cn"),
            new StringPair("核心系列2013", "m13/cn"),
            new StringPair("核心系列2012", "m12/cn"),
            new StringPair("Magic 2011", "m11/cn"),
            new StringPair("Magic 2010", "m10/cn"),
            new StringPair("第十版", "10e/cn"),
            new StringPair("第九版", "9e/cn"),
            new StringPair("Conspiracy", "cns/cn"),
            new StringPair("Modern Masters 2015 Edition", "mm2/cn"),
            new StringPair("Commander 2015", "c15/cn"),
            new StringPair("Commander 2014 Edition", "c14/cn"),
            new StringPair("Ninth Edition Box Set", "9eb/cn"),
            new StringPair("Portal Three Kingdoms", "p/cn"),

            new StringPair("Shadows over Innistrad", "soi"),
            new StringPair("Oath of the Gatewatch", "ogw"),
            new StringPair("Battle for Zendikar", "bfz"),
            new StringPair("Dragons of Tarkir", "dtk"),
            new StringPair("Fate Reforged", "frf"),
            new StringPair("Khans of Tarkir", "ktk"),
            new StringPair("Journey into Nyx", "jou"),
            new StringPair("Born of the Gods", "bng"),
            new StringPair("Theros", "ths"),
            new StringPair("Dragon's Maze", "dgm"),
            new StringPair("Gatecrash", "gtc"),
            new StringPair("Return to Ravnica", "rtr"),
            new StringPair("Avacyn Restored", "avr"),
            new StringPair("Dark Ascension", "dka"),
            new StringPair("Innistrad", "isd"),
            new StringPair("New Phyrexia", "nph"),
            new StringPair("Mirrodin Besieged", "mbs"),
            new StringPair("Scars of Mirrodin", "som"),
            new StringPair("Rise of the Eldrazi", "roe"),
            new StringPair("Worldwake", "wwk"),
            new StringPair("Zendikar", "zen"),
            new StringPair("Alara Reborn", "arb"),
            new StringPair("Conflux", "cfx"),
            new StringPair("Shards of Alara", "ala"),
            new StringPair("Eventide", "eve"),
            new StringPair("Shadowmoor", "shm"),
            new StringPair("Morningtide", "mt"),
            new StringPair("Lorwyn", "lw"),
            new StringPair("Future Sight", "fut"),
            new StringPair("Planar Chaos", "pc"),
            new StringPair("Time Spiral", "ts"),
            new StringPair("Time Spiral \"Timeshifted\"", "tsts"),
            new StringPair("Coldsnap", "cs"),
            new StringPair("Alliances", "ai"),
            new StringPair("Ice Age", "ia"),
            new StringPair("Dissension", "di"),
            new StringPair("Guildpact", "gp"),
            new StringPair("Ravnica: City of Guilds", "rav"),
            new StringPair("Saviors of Kamigawa", "sok"),
            new StringPair("Betrayers of Kamigawa", "bok"),
            new StringPair("Champions of Kamigawa", "chk"),
            new StringPair("Fifth Dawn", "5dn"),
            new StringPair("Darksteel", "ds"),
            new StringPair("Mirrodin", "mi"),
            new StringPair("Scourge", "sc"),
            new StringPair("Legions", "le"),
            new StringPair("Onslaught", "on"),
            new StringPair("Judgment", "ju"),
            new StringPair("Torment", "tr"),
            new StringPair("Odyssey", "od"),
            new StringPair("Apocalypse", "ap"),
            new StringPair("Planeshift", "ps"),
            new StringPair("Invasion", "in"),
            new StringPair("Prophecy", "pr"),
            new StringPair("Nemesis", "ne"),
            new StringPair("Mercadian Masques", "mm"),
            new StringPair("Urza's Destiny", "ud"),
            new StringPair("Urza's Legacy", "ul"),
            new StringPair("Urza's Saga", "us"),
            new StringPair("Exodus", "ex"),
            new StringPair("Stronghold", "sh"),
            new StringPair("Tempest", "tp"),
            new StringPair("Weatherlight", "wl"),
            new StringPair("Visions", "vi"),
            new StringPair("Mirage", "mr"),
            new StringPair("Homelands", "hl"),
            new StringPair("Fallen Empires", "fe"),
            new StringPair("The Dark", "dk"),
            new StringPair("Legends", "lg"),
            new StringPair("Antiquities", "aq"),
            new StringPair("Arabian", "Nights "),
            new StringPair("Magic Origins", "ori"),
            new StringPair("Magic 2015", "m15"),
            new StringPair("Magic 2014 Core Set", "m14"),
            new StringPair("Magic 2013", "m13"),
            new StringPair("Magic 2012", "m12"),
            new StringPair("Magic 2011", "m11"),
            new StringPair("Magic 2010", "m10"),
            new StringPair("Tenth Edition", "10e"),
            new StringPair("Ninth Edition", "9e"),
            new StringPair("Eighth Edition", "8e"),
            new StringPair("Seventh Edition", "7e"),
            new StringPair("Classic Sixth Edition", "6e"),
            new StringPair("Fifth Edition", "5e"),
            new StringPair("Fourth Edition", "4e"),
            new StringPair("Revised Edition", "rv"),
            new StringPair("Unlimited Edition", "un"),
            new StringPair("Limited Edition Beta", "be"),
            new StringPair("Limited Edition Alpha", "al"),
            new StringPair("Vintage Masters", "vma"),
            new StringPair("MTGO Masters Edition IV", "me4"),
            new StringPair("MTGO Masters Edition III", "me3"),
            new StringPair("MTGO Masters Edition II", "me2"),
            new StringPair("MTGO Masters Edition", "med"),
            new StringPair("Conspiracy", "cns"),
            new StringPair("Premium Deck Series: Graveborn", "pd3"),
            new StringPair("Premium Deck Series: Fire and Lightning", "pd2"),
            new StringPair("Premium Deck Series: Slivers", "pds"),
            new StringPair("Modern Masters 2015 Edition", "mm2"),
            new StringPair("Tempest Remastered", "tpr"),
            new StringPair("Modern Event Deck", "md1"),
            new StringPair("Modern Masters", "mma"),
            new StringPair("Duels of the Planeswalkers", "dpa"),
            new StringPair("Chronicles", "ch"),
            new StringPair("Commander 2015", "c15"),
            new StringPair("Commander 2014 Edition", "c14"),
            new StringPair("Commander 2013 Edition", "c13"),
            new StringPair("Commander's Arsenal", "cma"),
            new StringPair("Planechase 2012 Edition", "pc2"),
            new StringPair("Commander", "cmd"),
            new StringPair("Archenemy", "arc"),
            new StringPair("Planechase", "pch"),
            new StringPair("From the Vault: Angels", "v15"),
            new StringPair("From the Vault: Annihilation", "v14"),
            new StringPair("From the Vault: Twenty", "v13"),
            new StringPair("From the Vault: Realms", "v12"),
            new StringPair("From the Vault: Legends", "fvl"),
            new StringPair("From the Vault: Relics", "fvr"),
            new StringPair("From the Vault: Exiled", "fve"),
            new StringPair("From the Vault: Dragons", "fvd"),
            new StringPair("Duel Decks: Blessed vs. Cursed", "ddq"),
            new StringPair("Duel Decks: Zendikar vs. Eldrazi", "ddp"),
            new StringPair("Duel Decks Anthology: Divine vs. Demonic", "ddadvd"),
            new StringPair("Duel Decks Anthology: Elves vs. Goblins", "ddaevg"),
            new StringPair("Duel Decks Anthology: Garruk vs. Liliana", "ddagvl"),
            new StringPair("Duel Decks Anthology: Jace vs. Chandra", "ddajvc"),
            new StringPair("Duel Decks: Kiora vs. Elspeth", "ddo"),
            new StringPair("Duel Decks: Speed vs. Cunning", "ddn"),
            new StringPair("Duel Decks: Jace vs. Vraska", "ddm"),
            new StringPair("Duel Decks: Heroes vs. Monsters", "ddl"),
            new StringPair("Duel Decks: Sorin vs. Tibalt", "ddk"),
            new StringPair("Duel Decks: Izzet vs. Golgari", "ddj"),
            new StringPair("Duel Decks: Venser vs. Koth", "ddi"),
            new StringPair("Duel Decks: Ajani vs. Nicol Bolas", "ddh"),
            new StringPair("Duel Decks: Knights vs. Dragons", "ddg"),
            new StringPair("Duel Decks: Elspeth vs. Tezzeret", "ddf"),
            new StringPair("Duel Decks: Phyrexia vs. The Coalition", "pvc"),
            new StringPair("Duel Decks: Garruk vs. Liliana", "gvl"),
            new StringPair("Duel Decks: Divine vs. Demonic", "dvd"),
            new StringPair("Duel Decks: Jace vs. Chandra", "jvc"),
            new StringPair("Duel Decks: Elves vs. Goblins", "evg"),
            new StringPair("Coldsnap Theme Decks", "cstd"),
            new StringPair("Ninth Edition Box Set", "9eb"),
            new StringPair("Eighth Edition Box Set", "8eb"),
            new StringPair("Deckmasters", "dm"),
            new StringPair("Beatdown Box Set", "bd"),
            new StringPair("Battle Royale Box Set", "br"),
            new StringPair("Anthologies", "at"),
            new StringPair("Multiverse Gift Box Cards", "mgbc"),
            new StringPair("Unhinged", "uh"),
            new StringPair("Unglued", "ug"),
            new StringPair("Unhinged Alternate Foils", "uhaa"),
            new StringPair("Starter 2000", "st2k"),
            new StringPair("Starter 1999", "st"),
            new StringPair("Portal Three Kingdoms", "p3k"),
            new StringPair("Portal Second Age", "po2"),
            new StringPair("Portal", "po"),
            new StringPair("Introductory Two-Player Set", "itp"),
            new StringPair("Collector's Edition", "ced"),
            new StringPair("International Collectors' Edition", "cedi"),
            new StringPair("Zendikar Expeditions", "exp"),
            new StringPair("Ugin's Fate", "ugin"),
            new StringPair("15th Anniversary", "15ann"),
            new StringPair("Grand Prix", "gpx"),
            new StringPair("Pro Tour", "pro"),
            new StringPair("Magic Game Day Cards", "mgdc"),
            new StringPair("Worlds", "wrl"),
            new StringPair("World Magic Cup Qualifiers", "wmcq"),
            new StringPair("Dragon Con", "drc"),
            new StringPair("Prerelease Events", "ptc"),
            new StringPair("Release Events", "rep"),
            new StringPair("Magic: The Gathering Launch Parties", "mlp"),
            new StringPair("Summer of Magic", "sum"),
            new StringPair("WPN/Gateway", "grc"),
            new StringPair("Champs", "cp"),
            new StringPair("Two-Headed Giant Tournament", "thgt"),
            new StringPair("Arena League", "arena"),
            new StringPair("Friday Night Magic", "fnmp"),
            new StringPair("Magic Player Rewards", "mprp"),
            new StringPair("Super Series", "sus"),
            new StringPair("Happy Holidays", "hho"),
            new StringPair("Judge Gift Program", "jr"),
            new StringPair("Portal Demogame", "pot"),
            new StringPair("European Land Program", "euro"),
            new StringPair("Guru", "guru"),
            new StringPair("Asia Pacific Land Program", "apac"),
            new StringPair("WotC Online Store", "wotc"),
            new StringPair("Celebration Cards", "uqc"),
            new StringPair("Clash Pack", "clash"),
            new StringPair("Media Inserts", "mbp"),
            new StringPair("Legend Membership", "dcilm"),
    };

    public static String getAbbFromEditionName(String edition) {
        for (StringPair stringPair : AllEdition) {
            if (stringPair.first.equals(edition)) {
                return stringPair.second;
            }
        }
        return "";
    }
}
